index:
    path: /
    controller: App\Controller\DefaultController::index
authorization:
    path: /authorization
    controller: App\Controller\SecurityController::authorization
login:
    path: /login
    controller: App\Controller\SecurityController::login
user:
    path: /user/{slug}
    controller: App\Controller\UserController::show
app_logout:
    path: /logout
